// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJeAwdfaYlQQjv6Gj0SjZm4_SfZuKkKCc',
    appId: '1:1096048917266:web:684bf55495e0a6338351cb',
    messagingSenderId: '1096048917266',
    projectId: 'humosync-safety',
    authDomain: 'humosync-safety.firebaseapp.com',
    databaseURL: 'https://humosync-safety-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'humosync-safety.firebasestorage.app',
    measurementId: 'G-94YBSCXWJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH2OE0CY8-OgN5FJoRZ0gWNp-aQo4-2yk',
    appId: '1:1096048917266:android:6354aefb00a924b78351cb',
    messagingSenderId: '1096048917266',
    projectId: 'humosync-safety',
    databaseURL: 'https://humosync-safety-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'humosync-safety.firebasestorage.app',
  );
}
